README-src.md
README.md

Doc: Add README for assignment and change name of old README

---

src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java
src/test/resources/data/typicalDataBundle.json

Add unit test for `checkSpecificAccessControl` to verify that exception is thrown when an instructor to a question does not exist.
Fixes #23

Feat: Add test for non-existing instructor (#23)

---

src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java

Add unit test for checkSpecificAccessControl to verify that exception is thrown when an incorrect intent is used.
Fixes #25

Feat: Add test for unknown/incorrect intent (#25)

---

src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java

feat: add test for unknown intent (#30)

---

src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java

resolves #49

---

src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java
src/test/resources/data/typicalDataBundle.json

resolves #22

---

src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java

resolves #24

---

src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java

Add unit test to validate student's submission in `execute()`. 
Fix: re-add previously removed test `testAccessControl_feedbackQuestionDoesNotExist_shouldThrowEntityNotFoundException()`.
Fixes #34

Feat: Add test for valid student submission (#34)

---

README.md

Fixes #12 
Adds tables with the identified requirements to the `README` in an easily digestible format.

Doc: Add identified requirements to `README` (#12)

---

src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java

feat: add test for invalid recipient (#31)

---

src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java

Fixes #37 
Adds a test for the case where we modify an already existing response.

Feat: Add test for update response (ex08)

---

README.md

[#11] README "Overview of issues and work done"

---

README.md

[#2] Add "P+ points aimed for" section

---

src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java

fix: logout after test (#64)

---

src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java

fix: login and logout in test (#65)

---

src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java

feat: Add test for valid instructor submission (#35)

---

README.md

Fill in hours for Markus. (#9)

README: Fill in hours under "Effort spent" 

---

src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java

Feat: Add test for ex10 (#45)

---

src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java
src/test/resources/data/typicalDataBundle.json

Feat: Add test for ex11 (#39)

---

src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java

Work on #60 
Added some helper functions as well as a helper class to retrieve and hold data used for most tests.
We don't save *that* much in terms of lines but I think the individual tests get easier to follow.
Feel free to give your opinion on whether we want this for the project.

Refactor tests to mitigate code duplication (#60)

---

src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java
src/test/resources/data/typicalDataBundle.json

Feat: Add unit tests for ex03 and ex04 #36

---

src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java

Refactor tests for ex03 and ex04 (#80)

---

src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java

Fix bug in ex08 test (#75)

---

src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java
src/test/resources/data/typicalDataBundle.json

Fix: Restore `typicalDataBundle.json` (#74)

---

src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java

feat: add test for adding response if no existing response (#42)

---

README.md

doc: Added link to overview and purpose of system (#17)

---

README.md

Doc: Add test results to `README` (#14)

---

README.md

Doc: Add patch information to README (#84)
